dataset:
  scene_boundary: [-50, -50, -10, 250, 200, 60]
  colmap_dir: "D:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align"
  superglue_dir: "D:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align/superpoint"
  segments_dir: "D:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align/segments"
  mesh_dir: "D:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align/detailed_l7.ply"
  img_size: [6000,4000]

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0

  batch_size: 2
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

  output: neural_recon

model:
  model_name: Uncertainty_Modeling


hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled