dataset:
  dataset_name: ABC_dataset_patch_hdf5
  v_output_features: 4
  test_list: ["G:/Dataset/ABC/GSP_comparison_4/00860128/00860128_656134f148f7f10848eaa437_trimesh_000.obj"]

trainer:
  gpu: 1

  batch_size: 128
  resume_from_checkpoint: output/neural_bsp/0815_26k_focal_residual.ckpt
  output: .
  accelerator: "16-mixed"

model:
  model_name: TestNetResidualSE
  v_input_channel: 4

  v_depth: 5
  v_base_channel: 32

#  phase: [32,64,128,256,512,1024]
  phase: [16, 32, 64, 128, 256]

  loss: BCE_loss
  loss_alpha: 0.75

  test_threshold: 0.7
  test_resolution: 256


hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
