dataset:
  root: G:/Dataset/GSP/GSP_v7_1k/training.hdf5
  dataset_name: ABC_dataset_overlap
#  dataset_name: ABC_dataset_sparse_features
  patch_size: 32
  input_density: 4
  query_density: 2

  test_list: []
#  test_list: ["00860128","00860559","00860889","00861617"]
#  test_list: ["00015724"]

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 8

  batch_size: 1
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 1
  accelerator: "16-mixed"

model:
  model_name: Base_model
  depths: 4

  fc_hidden_dim: 64
  max_voxel_dim: 64
  need_normalize: true

  fmaps: [16, 32, 64, 128, 256]
  channels: 7

  test_threshold: 0.5

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled