dataset:
#  root: C:\repo\python\src\neural_bsp\train.hdf5
  root: F:\GSP\GSP_v3\training
#  dataset_name: ABC_dataset_patch_hdf5
  dataset_name: ABC_dataset_patch

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 2

  batch_size: 160
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 1

model:
  model_name: Base_model_full
  phase: 0

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled