dataset:
#  root: G:\Dataset\GSP_v3_part\total_1k.hdf5
  root: F:\GSP\GSP_comparison_v4_4\training
#  dataset_name: ABC_dataset_patch_hdf5
  dataset_name: ABC_dataset_patch_train_dir
#  test_list: []
  test_list: ["00860128","00860559","00860889","00861617"]

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 4

  batch_size: 128
  validation_batch_size: 512
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 1
  accelerator: "32-true"

model:
  model_name: TestNetResidualSE
  phase: 0
  test_threshold: 0.5
  loss: BCE_loss
  loss_alpha: 0.75

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled