dataset:
  root: G:\Dataset\ABC\GSP_v3_part_1k\training
#  root: F:/GSP/GSP_v3_part/training_1k.hdf5
  dataset_name: ABC_dataset_patch_test
  v_output_features: 4
#  test_list: []
  test_list: []
#  test_list: ["00860128","00860559","00860889","00861617"]
#  test_list: ["00015724"]

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0

  batch_size: 128
  validation_batch_size: 256
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 1
  accelerator: "16-mixed"

model:
  model_name: TestNetResidualSE
  v_input_channel: 4
  v_depth: 5
  v_base_channel: 32
  phase: [32, 64, 128, 256, 512, 1024]
#  phase: [16, 32, 64, 128, 256]

  loss: BCE_loss
  loss_alpha: 0.75

  test_threshold: 0.5


hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled