trainer:
  learning_rate: 1e-5
  gpu: 1
  num_worker: 16
#  dataset_name: Regress_hyper_parameters_dataset_with_imgs_with_truncated_error
  dataset_name: Regress_hyper_parameters_dataset_with_imgs
  dataset_root: D:/Projects/Reconstructability/training_data/v6/

  train_dataset: chengbao_fine_ds_0090*chengbao_fine_ds_0070*chengbao_fine_dp_0090*chengbao_fine_dp_0070*chengbao_fine_sm_0090*chengbao_fine_sm_0070*chengbao_preview_ds_0090*chengbao_preview_ds_0070*chengbao_preview_dp_0090*chengbao_preview_dp_0070*chengbao_preview_sm_0090*chengbao_preview_sm_0070*qiao_fine_ds_0090*qiao_fine_ds_0070*qiao_fine_dp_0090*qiao_fine_dp_0070*qiao_fine_sm_0090*qiao_fine_sm_0070*qiao_preview_ds_0090*qiao_preview_ds_0070*qiao_preview_dp_0090*qiao_preview_dp_0070*qiao_preview_sm_0090*qiao_preview_sm_0070*xuexiao_fine_ds_0090*xuexiao_fine_ds_0070*xuexiao_fine_dp_0090*xuexiao_fine_dp_0070*xuexiao_fine_sm_0090*xuexiao_fine_sm_0070*xuexiao_preview_ds_0090*xuexiao_preview_ds_0070*xuexiao_preview_dp_0090*xuexiao_preview_dp_0070*xuexiao_preview_sm_0090*xuexiao_preview_sm_0070
  valid_dataset: xiaozhen_fine_ds_0090*xiaozhen_fine_ds_0070*xiaozhen_fine_dp_0090*xiaozhen_fine_dp_0070*xiaozhen_fine_sm_0090*xiaozhen_fine_sm_0070*xiaozhen_preview_ds_0090*xiaozhen_preview_ds_0070*xiaozhen_preview_dp_0090*xiaozhen_preview_dp_0070*xiaozhen_preview_sm_0090*xiaozhen_preview_sm_0070
  test_dataset: xiaozhen_fine_ds_0090*xiaozhen_fine_ds_0070*xiaozhen_fine_dp_0090*xiaozhen_fine_dp_0070*xiaozhen_fine_sm_0090*xiaozhen_fine_sm_0070*xiaozhen_preview_ds_0090*xiaozhen_preview_ds_0070*xiaozhen_preview_dp_0090*xiaozhen_preview_dp_0070*xiaozhen_preview_sm_0090*xiaozhen_preview_sm_0070

  loss: loss_l2_recon

  batch_size: 128
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

model:
  model_name: Uncertainty_Modeling_wo_pointnet14
  involve_img: false
  open_weights: true
  num_points_per_batch: 1
  view_mean_std: [1.0275,-0.7300,1.3202,0.6542,0.4880,0.3769,1.7259,0.6673,0.2400,0.4130]
  error_mean_std: [0.015,0.015,0.015,0.015]
  spearman_method: l2
  spearman_factor: 1.0
  add_bias_kv: false
  use_scaled_loss: true

hydra:
  run:
    dir: .
  output_subdir: null
