trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0
  train_dataset: D:\Projects\Reconstructability\pre_computed\ds_fine_trajectory_fine_proxy_school\training_data*D:\Projects\Reconstructability\pre_computed\ds_inter_trajectory_inter_proxy_bridge\training_data*D:\Projects\Reconstructability\pre_computed\ds_coarse_trajectory_coarse_proxy_school\training_data
  valid_dataset: D:\Projects\Reconstructability\pre_computed\smith_inter_trajectory_inter_proxy_bridge\training_data
  test_dataset: D:\Projects\Reconstructability\pre_computed\ds_fine_trajectory_fine_proxy_school\training_data
  loss: loss_truncated_entropy

  batch_size: 2
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

model:
  model_name: Uncertainty_Modeling
  involve_img: true
  open_weights: true
  num_points_per_batch: 256

hydra:
  run:
    dir: .
  output_subdir: null
