trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 2
  train_dataset: D:\DATASET\KITTI\3DDetection\data_object_image_2\training
  valid_dataset: D:\DATASET\KITTI\3DDetection\data_object_image_2\training

  batch_size: 8
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

model:
  model_name: Uncertainty_Modeling
  is_preprocess: false
  preprocess_path: /mnt/d/reconstructability/regress_test_proxy_10k/
  target_data_dir: D:\Projects\Reconstructability\Scene\bridge_45K\default_noredundancy_nominmax\log
  error_point_cloud_dir: D:\Projects\Reconstructability\Scene\bridge_45K\completeness_smith.ply
  img_size: (600,400)

  img_dir: D:\Projects\Building_data\Bridge\asia18\images

  involve_img: true
  num_points_per_batch: 256

hydra:
  run:
    dir: .
  output_subdir: null
